frama-c -wp -wp-prover cvc5  ./01-abs-0.c >> output_cvc5.txt
frama-c -wp -wp-prover cvc5  ./01-abs-1.c >> output_cvc5.txt
frama-c -wp -wp-prover cvc5  ./01-abs-2.c >> output_cvc5.txt
frama-c -wp -wp-prover cvc5  ./01-abs-3.c >> output_cvc5.txt
frama-c -wp -wp-prover cvc5  ./02-max-0.c >> output_cvc5.txt
frama-c -wp -wp-prover cvc5  ./02-max-1.c >> output_cvc5.txt
frama-c -wp -wp-prover cvc5  ./02-max-2.c >> output_cvc5.txt
frama-c -wp -wp-prover cvc5  ./02-max-3.c >> output_cvc5.txt
frama-c -wp -wp-prover cvc5  ./02-max-4.c >> output_cvc5.txt
frama-c -wp -wp-prover cvc5  ./03-max_ptr-0.c >> output_cvc5.txt
frama-c -wp -wp-prover cvc5  ./03-max_ptr-1.c >> output_cvc5.txt
frama-c -wp -wp-prover cvc5  ./03-max_ptr-2.c >> output_cvc5.txt
frama-c -wp -wp-prover cvc5  ./03-max_ptr-3.c >> output_cvc5.txt
frama-c -wp -wp-prover cvc5  ./03-max_ptr-4.c >> output_cvc5.txt
frama-c -wp -wp-prover cvc5  ./04-incr_a_by_b-0.c >> output_cvc5.txt
frama-c -wp -wp-prover cvc5  ./04-incr_a_by_b-1.c >> output_cvc5.txt
frama-c -wp -wp-prover cvc5  ./04-incr_a_by_b-fail.c >> output_cvc5.txt
frama-c -wp -wp-prover cvc5  ./04-swap-0.c >> output_cvc5.txt
frama-c -wp -wp-prover cvc5  ./04-swap-1.c >> output_cvc5.txt
frama-c -wp -wp-prover cvc5  ./05-abs-0.c >> output_cvc5.txt
frama-c -wp -wp-prover cvc5  ./05-abs-1.c >> output_cvc5.txt
frama-c -wp -wp-prover cvc5  ./05-abs-2.c >> output_cvc5.txt
frama-c -wp -wp-prover cvc5  ./06-max_abs-0.c >> output_cvc5.txt
frama-c -wp -wp-prover cvc5  ./06-max_abs-1.c >> output_cvc5.txt
frama-c -wp -wp-prover cvc5  ./06-max_abs-2.c >> output_cvc5.txt
frama-c -wp -wp-prover cvc5  ./06-max_abs-3.c >> output_cvc5.txt
frama-c -wp -wp-prover cvc5  ./07-reset_array-0.c >> output_cvc5.txt
frama-c -wp -wp-prover cvc5  ./07-reset_array-1.c >> output_cvc5.txt
frama-c -wp -wp-prover cvc5  ./08-binary_search-1.c >> output_cvc5.txt
frama-c -wp -wp-prover cvc5  ./09-sqrt-0.c >> output_cvc5.txt